export const ACTION_IDS = {
  app_mounted: "app.mounted",
  app_editor_mount: "app.editor.mount",
  app_editor_unmount: "app.editor.unmount",

  note_create: "note.create",
  note_open: "note.open",
  note_open_wiki_link: "note.open_wiki_link",
  note_insert_pasted_image: "note.insert_pasted_image",
  note_request_image_paste: "note.request_image_paste",
  note_update_image_paste_filename: "note.update_image_paste_filename",
  note_confirm_image_paste: "note.confirm_image_paste",
  note_cancel_image_paste: "note.cancel_image_paste",
  note_copy_markdown: "note.copy_markdown",
  note_request_delete: "note.request_delete",
  note_confirm_delete: "note.confirm_delete",
  note_cancel_delete: "note.cancel_delete",
  note_request_rename: "note.request_rename",
  note_update_rename_name: "note.update_rename_name",
  note_confirm_rename: "note.confirm_rename",
  note_confirm_rename_overwrite: "note.confirm_rename_overwrite",
  note_cancel_rename: "note.cancel_rename",
  note_retry_rename: "note.retry_rename",
  note_request_save: "note.request_save",
  note_update_save_path: "note.update_save_path",
  note_confirm_save: "note.confirm_save",
  note_confirm_save_overwrite: "note.confirm_save_overwrite",
  note_retry_save: "note.retry_save",
  note_cancel_save: "note.cancel_save",

  vault_request_change: "vault.request_change",
  vault_close_change: "vault.close_change",
  vault_choose: "vault.choose",
  vault_select: "vault.select",
  vault_reindex: "vault.reindex",

  folder_request_create: "folder.request_create",
  folder_update_create_name: "folder.update_create_name",
  folder_confirm_create: "folder.confirm_create",
  folder_cancel_create: "folder.cancel_create",
  folder_toggle: "folder.toggle",
  folder_load_more: "folder.load_more",
  folder_retry_load: "folder.retry_load",
  folder_collapse_all: "folder.collapse_all",
  folder_refresh_tree: "folder.refresh_tree",
  folder_request_delete: "folder.request_delete",
  folder_confirm_delete: "folder.confirm_delete",
  folder_cancel_delete: "folder.cancel_delete",
  folder_retry_delete: "folder.retry_delete",
  folder_request_rename: "folder.request_rename",
  folder_update_rename_name: "folder.update_rename_name",
  folder_confirm_rename: "folder.confirm_rename",
  folder_cancel_rename: "folder.cancel_rename",
  folder_retry_rename: "folder.retry_rename",

  ui_toggle_sidebar: "ui.toggle_sidebar",
  ui_select_folder: "ui.select_folder",
  ui_set_theme: "ui.set_theme",

  settings_open: "settings.open",
  settings_close: "settings.close",
  settings_update: "settings.update",
  settings_save: "settings.save",

  omnibar_toggle: "omnibar.toggle",
  omnibar_open: "omnibar.open",
  omnibar_close: "omnibar.close",
  omnibar_set_query: "omnibar.set_query",
  omnibar_set_selected_index: "omnibar.set_selected_index",
  omnibar_confirm_item: "omnibar.confirm_item",

  find_in_file_toggle: "find_in_file.toggle",
  find_in_file_open: "find_in_file.open",
  find_in_file_close: "find_in_file.close",
  find_in_file_set_query: "find_in_file.set_query",
  find_in_file_next: "find_in_file.next",
  find_in_file_prev: "find_in_file.prev",
} as const;

export type ActionId = (typeof ACTION_IDS)[keyof typeof ACTION_IDS];
